language: node_js

node_js:
  - '6'

before_install:
  - openssl aes-256-cbc -K $encrypted_304834ef0277_key -iv $encrypted_304834ef0277_iv
    -in .deploy.key.enc -out deploy.key -d
script:
  - npm run build_api
  - npm run build

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./.deploy.sh; fi'
