language: node_js
before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_304834ef0277_key -iv $encrypted_304834ef0277_iv -in .deploy.key.enc -out deploy.key -d; fi'

script:
  - make lint
  - make build

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then bash ./.deploy.sh; fi'
