language: node_js

node_js:
  - '6'

before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_304834ef0277_key -iv $encrypted_304834ef0277_iv -in .deploy.key.enc -out deploy.key -d; fi'

script:
  - make build

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./.deploy.sh; fi'
