define('dojo/nls/dojo_ROOT',{
'dijit/nls/loading':{"loadingState":"Loading...","errorState":"Sorry, an error occurred","_localized":{"ar":1,"az":1,"bg":1,"ca":1,"cs":1,"da":1,"de":1,"el":1,"es":1,"fi":1,"fr":1,"he":1,"hr":1,"hu":1,"it":1,"ja":1,"kk":1,"ko":1,"nb":1,"nl":1,"pl":1,"pt":1,"pt-pt":1,"ro":1,"ru":1,"sk":1,"sl":1,"sv":1,"th":1,"tr":1,"uk":1,"zh":1,"zh-tw":1}}
,
'dijit/nls/common':{"buttonOk":"OK","buttonCancel":"Cancel","buttonSave":"Save","itemClose":"Close","_localized":{"ar":1,"az":1,"bg":1,"ca":1,"cs":1,"da":1,"de":1,"el":1,"es":1,"fi":1,"fr":1,"he":1,"hr":1,"hu":1,"it":1,"ja":1,"kk":1,"ko":1,"nb":1,"nl":1,"pl":1,"pt":1,"pt-pt":1,"ro":1,"ru":1,"sk":1,"sl":1,"sv":1,"th":1,"tr":1,"uk":1,"zh":1,"zh-tw":1}}
,
'dijit/form/nls/validate':{"invalidMessage":"The value entered is not valid.","missingMessage":"This value is required.","rangeMessage":"This value is out of range.","_localized":{"ar":1,"az":1,"bg":1,"ca":1,"cs":1,"da":1,"de":1,"el":1,"es":1,"fi":1,"fr":1,"he":1,"hr":1,"hu":1,"it":1,"ja":1,"kk":1,"ko":1,"nb":1,"nl":1,"pl":1,"pt":1,"pt-pt":1,"ro":1,"ru":1,"sk":1,"sl":1,"sv":1,"th":1,"tr":1,"uk":1,"zh":1,"zh-tw":1}}
,
'dijit/form/nls/ComboBox':{"previousMessage":"Previous choices","nextMessage":"More choices","_localized":{"ar":1,"az":1,"bg":1,"ca":1,"cs":1,"da":1,"de":1,"el":1,"es":1,"fi":1,"fr":1,"he":1,"hr":1,"hu":1,"it":1,"ja":1,"kk":1,"ko":1,"nb":1,"nl":1,"pl":1,"pt":1,"pt-pt":1,"ro":1,"ru":1,"sk":1,"sl":1,"sv":1,"th":1,"tr":1,"uk":1,"zh":1,"zh-tw":1}}
,
'dojox/form/nls/Uploader':{"label":"Select Files...","_localized":{"ar":1,"ca":1,"cs":1,"da":1,"de":1,"el":1,"es":1,"fi":1,"fr":1,"he":1,"hr":1,"hu":1,"it":1,"ja":1,"kk":1,"ko":1,"nb":1,"nl":1,"pl":1,"pt":1,"pt-pt":1,"ro":1,"ru":1,"sk":1,"sl":1,"sv":1,"th":1,"tr":1,"zh":1,"zh-tw":1}}
,
'dojo/cldr/nls/number':{"scientificFormat":"#E0","currencySpacing-afterCurrency-currencyMatch":"[:letter:]","infinity":"∞","list":";","percentSign":"%","minusSign":"-","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","decimalFormat-short":"000T","currencySpacing-afterCurrency-insertBetween":" ","nan":"NaN","plusSign":"+","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-currencyMatch":"[:letter:]","currencyFormat":"¤ #,##0.00","perMille":"‰","group":",","percentFormat":"#,##0%","decimalFormat-long":"000T","decimalFormat":"#,##0.###","decimal":".","currencySpacing-beforeCurrency-insertBetween":" ","exponential":"E","_localized":{"ar":1,"ca":1,"cs":1,"da":1,"de":1,"el":1,"en":1,"en-au":1,"en-gb":1,"es":1,"fi":1,"fr":1,"fr-ch":1,"he":1,"hu":1,"it":1,"ja":1,"ko":1,"nb":1,"nl":1,"pl":1,"pt":1,"pt-pt":1,"ro":1,"ru":1,"sk":1,"sl":1,"sv":1,"th":1,"tr":1,"zh":1,"zh-hant":1,"zh-hk":1,"zh-tw":1}}
});